# Generated by Django 3.2 on 2022-03-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('MedicineName', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('medicineId', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('amount', models.IntegerField(default=0, null=True)),
                ('issueQuantity', models.IntegerField(default=0, null=True)),
                ('reorderLevel', models.IntegerField(null=True)),
                ('issueTo', models.CharField(max_length=50, null=True)),
                ('receivedBy', models.CharField(max_length=50, null=True)),
                ('receiveQuantity', models.IntegerField(default=0, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pharmacistName', models.CharField(max_length=30)),
                ('joining_date', models.DateField()),
                ('phone', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('added_on', models.DateTimeField()),
            ],
        ),
    ]
