# Generated by Django 3.2.9 on 2021-11-30 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PharmacyManagementSystem', '0002_delete_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceNumber', models.IntegerField()),
                ('itemOne', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='item 1')),
                ('itemOne_Quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('itemOne_Unit_Price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price(D)')),
                ('itemOne_total_Price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total(D)')),
                ('itemTwo', models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='Line 2')),
                ('itemTwo_Quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('itemTwo_Unit_Price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price(D)')),
                ('itemTwo_total_Price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total(D)')),
                ('itemThree', models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='Line 3')),
                ('itemThree_Quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('itemThree_Unit_Price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price(D)')),
                ('itemThree_total_Price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total(D)')),
                ('itemFour', models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='Line 4')),
                ('itemFour_Quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('itemFour_Unit_Price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price(D)')),
                ('itemFour_total_Price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total(D)')),
                ('itemFive', models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='Line 5')),
                ('itemFive_Quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('itemFive_Unit_Price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price(D)')),
                ('itemFive_total_Price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total(D)')),
                ('phone_number', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('total', models.IntegerField(blank=True, default=0, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('firstName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PharmacyManagementSystem.customer')),
            ],
        ),
    ]
