# Generated by Django 3.2.9 on 2021-12-01 11:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PharmacyManagementSystem', '0003_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='itemFive',
            field=models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='Item 5'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='itemFour',
            field=models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='Item 4'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='itemOne',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Item 1'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='itemThree',
            field=models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='Item 3'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='itemTwo',
            field=models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='Item 2'),
        ),
    ]
