# Generated by Django 3.2.9 on 2022-02-19 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PharmacyManagementSystem', '0005_auto_20211206_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='customerId',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='medicineId',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='pharmacistName',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
