# Generated by Django 3.2.9 on 2021-12-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PharmacyManagementSystem', '0004_auto_20211201_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='amount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='receiveQuantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='salesId',
            field=models.AutoField(default=True, primary_key=True, serialize=False),
        ),
    ]
