# Generated by Django 3.2 on 2022-03-25 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PharmacyManagementSystem', '0001_initial'),
        ('Customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='height',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='medicine',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='PharmacyManagementSystem.medicine'),
        ),
        migrations.AddField(
            model_name='customer',
            name='weight',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
